name: Deploy to Github Pages
on:
    push:
      branches:
        - master
jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '12'
          - name: Set Creds
            run: git config --global user.name "zzbgreatman" && git config --global user.email "lzy968@gmail.com"
          - name: Deploy
            run: npm run deploy
